### ISSUE TITLE
Clarification Needed on Data Standards Used for Shoe Sizes

### ISSUE THREAD

**Issue by sarah-schuh** [alisonmonteiro/shoe-size-converter#10]
Hello,

let me start by saying "Thank you" ;-) 

I would like to inquire about the data used in the project. Could you please clarify whether the data is based on any standard norms, such as ISO standards, or if it is based on proprietary or "own" data? Understanding the basis of the data will help in accurately interpreting and utilizing it.

Thank you for your assistance.

Kind regards, 

Sarah

**Comment by cjblomqvist** [comment]
Appreciate the thanks!

It's documented in the code. Check the systems folder.

**Comment by sarah-schuh** [comment]
Thank you ever so much!! 

Sorry for asking such a n00b question and not checking carefully in code. 

I just started out and am new to github. 

Have a nice day!!

Sarah

**Comment by cjblomqvist** [comment]
No problems at all ☺️
