### ISSUE TITLE
Add support for Italian and French sizes

### ISSUE THREAD

**Issue by ThermScissorpunch** [alisonmonteiro/shoe-size-converter#9]
See table at Farfetch: https://www.farfetch.com/style-guide/brands/french-brands-and-french-sizing-guide/

![image](https://github.com/alisonmonteiro/shoe-size-converter/assets/61228862/e1c6e758-e88e-4812-9767-c4fa85f83187)

**Comment by cjblomqvist** [comment]
Are there any other sources on this? 

As far as I know EU sizing actually comes from France. In EU sizing one size step is equal to 2/3 of a cm, which is not the same as one size step in US/UK (based on inches). This size chart equals them though, which is quite surprising and confusing.

Unless there are more sources/proof of this I'd prefer not to add it. You can always easily add your own though in case you need Farfetches own special standard.
